### ISSUE TITLE
Failed to activate the windows-carriage-return-remover package

### ISSUE THREAD

**Issue by kyoh86** [acrogenesis/windows-carriage-return-remover#2]
1. Open a command palette
2. Input a "car"
3. Find a "Windows Carriage Return: Remove" command.
4. Enter.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [windows-carriage-return-remover](https://github.com/acrogenesis/windows-carriage-return-remover) package, v0.1.2
### Stack Trace

Failed to activate the windows-carriage-return-remover package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/kyoh/.atom/packages/windows-carriage-return-remover/lib/windows-carriage-return-remover.coffee:3:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:03.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 windows-carriage-return:remove (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "Sublime-Style-Column-Selection",
      "atom-ctags",
      "jumpy",
      "fancy-new-file",
      "file-icons",
      "marked",
      "linter-golinter"
    ],
    "themes": [
      "seti-ui",
      "tomorrow-night-syntax-theme"
    ],
    "projectHome": "/Users/kyoh/work/my-project/src/github.com"
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v4.5.13
autocomplete-php, v0.3.6
change-case, v0.6.0
color-picker, v2.0.4
column-select, v0.2.0
css-color-underline, v1.0.1
docblockr, v0.7.2
git-projects, v1.14.1
git-tab-status, v1.9.2
go-plus, v3.3.11
highlight-selected, v0.9.3
japanese-wrap, v0.2.10
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-js-yaml, v1.0.1
linter-jshint, v0.1.6
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-tslint, v0.2.2
pretty-json, v0.3.3
react, v0.12.0
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
tomorrow-night-syntax-theme, v0.2.0
windows-carriage-return-remover, v0.1.2

# Dev
No dev packages
```

**Comment by acrogenesis** [comment]
On it, i'll try and fix this today

**Comment by acrogenesis** [comment]
@kyoh86 thanks, I've release version `0.1.3` it should work know, I'm closing the issue, if you are still having trouble after updating please reopen it.
