### ISSUE TITLE
Uncaught TypeError: editor.getText is not a function

### ISSUE THREAD

**Issue by ivaylodimov** [acrogenesis/windows-carriage-return-remover#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [windows-carriage-return-remover](https://github.com/acrogenesis/windows-carriage-return-remover) package 0.1.3

### Stack Trace

Uncaught TypeError: editor.getText is not a function

```
At C:\Users\c5227588\.atom\packages\windows-carriage-return-remover\lib\windows-carriage-return-remover.coffee:6

TypeError: editor.getText is not a function
    at Object.remove (/packages/windows-carriage-return-remover/lib/windows-carriage-return-remover.coffee:6:27)
    at /packages/windows-carriage-return-remover/lib/windows-carriage-return-remover.coffee:3:79)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.0/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.0/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.0/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:53.1.0 windows-carriage-return-remover:toggle (div.tool-panel.tree-view)
     -0:43.7.0 command-palette:toggle (input.hidden-input)
     -0:36.8.0 windows-carriage-return:remove (input.hidden-input)
     -0:29.9.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:18.3.0 core:confirm (input.hidden-input)
     -0:18.3.0 windows-carriage-return:remove (div.tool-panel.tree-view)
```

### Non-Core Packages

```
language-chef 0.11.0 
linter-chefstyle 1.0.1 
windows-carriage-return-remover 0.1.3 
```

**Comment by tetrahedronix** [comment]
I'm not very sure but maybe it happens when trying to use the command `Window carriage return` on a window that doesn't contain text, for example the Settings View in Atom.

**Comment by acrogenesis** [comment]
Makes sense we could check first if `editor` exists
